<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bat</string>
		<string>cmd</string>
	</array>
	<key>firstLineMatch</key>
	<string>(?i)^@echo off$</string>
	<key>name</key>
	<string>DOS/Windows Batch File</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#batch</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>batch</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cmd-escape-caret</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-escape-for</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-escape-delayed</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-escape-find</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-parenthesis</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-keys</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-vars-exclam</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-vars-percent</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-vars-args</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-rem-colons</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-rem</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-echo-on</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-echo</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-title</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-set</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-if</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-setlocal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-reserved</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-net</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-com</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-exe</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-goto</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-internal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-indo</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-equ</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-label</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-string-double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-redirect</string>
				</dict>
			</array>
		</dict>
		<key>cmd-com</key>
		<dict>
			<key>match</key>
			<string>\b(?i)(chcp|diskcomp|diskcopy|format|mode|more|tree)(\.com)?\b</string>
			<key>name</key>
			<string>keyword.external.com.cmd</string>
		</dict>
		<key>cmd-echo</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.echo.cmd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.echo.cmd</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?i)(echo)\b(?!\s*/\?)(.*?)(?&lt;!\^)(?=$|&amp;|\||&lt;|&gt;)</string>
		</dict>
		<key>cmd-echo-on</key>
		<dict>
			<key>match</key>
			<string>\b(?i)echo\s+(on|off|/\?)\s*(?=$|&amp;|\||&lt;|&gt;)</string>
			<key>name</key>
			<string>keyword.echo.cmd</string>
		</dict>
		<key>cmd-equ</key>
		<dict>
			<key>match</key>
			<string>\b(?i)(?:equ|neq|lss|leq|gtr|geq)\b</string>
			<key>name</key>
			<string>keyword.operator.cmd</string>
		</dict>
		<key>cmd-escape-caret</key>
		<dict>
			<key>match</key>
			<string>\^[&amp;&lt;&gt;|^]|\^$</string>
			<key>name</key>
			<string>storage.type.escape.caret.cmd</string>
		</dict>
		<key>cmd-escape-delayed</key>
		<dict>
			<key>match</key>
			<string>\^\^!</string>
			<key>name</key>
			<string>storage.type.escape.delayed.cmd</string>
		</dict>
		<key>cmd-escape-find</key>
		<dict>
			<key>match</key>
			<string></string>
			<key>name</key>
			<string>storage.type.escape.find.cmd</string>
		</dict>
		<key>cmd-escape-for</key>
		<dict>
			<key>match</key>
			<string>\^['`,;=()]</string>
			<key>name</key>
			<string>storage.type.escape.for.cmd</string>
		</dict>
		<key>cmd-exe</key>
		<dict>
			<key>match</key>
			<string>\b(?i)(?&lt;!\.)(attrib|bcdedit|cacls|chkdsk|chkntfs|cmd|comp|compact|convert|diskpart|doskey|driverquery|fc|find|findstr|fsutil|gpresult|help|icacls|label|openfiles|print|recover|replace|robocopy|sc|schtasks|shutdown|sort|subst|systeminfo|taskkill|tasklist|wmic|xcopy|makecab|expand|regedit|reg|cmdow|cwnd|cscript|ping)(?!\\|\))(\.exe)?\b</string>
			<key>name</key>
			<string>keyword.external.exe.cmd</string>
		</dict>
		<key>cmd-goto</key>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=call|goto)\s*\w+</string>
			<key>name</key>
			<string>constant.other.colon.cmd</string>
		</dict>
		<key>cmd-if</key>
		<dict>
			<key>match</key>
			<string>\b(?i)(if|not|else|exist|defined|errorlevel|cmdextversion)\b</string>
			<key>name</key>
			<string>keyword.control.conditional.if.cmd</string>
		</dict>
		<key>cmd-indo</key>
		<dict>
			<key>match</key>
			<string>\b(?i)(?&lt;=\ )(in|do)(?=\ )\b</string>
			<key>name</key>
			<string>keyword.control.repeat.cmd</string>
		</dict>
		<key>cmd-internal</key>
		<dict>
			<key>match</key>
			<string>\b(?i)(?&lt;!\.)(assoc|break|call|cd|chdir|cls|color|copy|date|del|dir|echo|endlocal|erase|exit|for|ftype|goto|graftabl|if|md|mkdir|mklink|move|path|pause|popd|prompt|pushd|rd|rem|ren|rename|rmdir|set|setlocal|shift|start|time|title|type|ver|verify|vol)(?!\\)\b</string>
			<key>name</key>
			<string>keyword.internal.cmd</string>
		</dict>
		<key>cmd-keys</key>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=[a-z =])/(\?|[a-z:/-]+)</string>
			<key>name</key>
			<string>support.function.key.cmd</string>
		</dict>
		<key>cmd-label</key>
		<dict>
			<key>match</key>
			<string>:\w+</string>
			<key>name</key>
			<string>constant.other.colon.cmd</string>
		</dict>
		<key>cmd-net</key>
		<dict>
			<key>match</key>
			<string>\b(?i)net(\.exe)?\s+(accounts|computer|config|continue|file|group|help|helpmsg|localgroup|pause|session|share|start|statistics|stop|time|use|user|view)\b</string>
			<key>name</key>
			<string>keyword.net.exe.cmd</string>
		</dict>
		<key>cmd-parenthesis</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>markup.inserted.cmd</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#batch</string>
				</dict>
			</array>
		</dict>
		<key>cmd-redirect</key>
		<dict>
			<key>match</key>
			<string>&amp;&amp;|&amp;|\|\||\||&amp;&gt;|\d?&gt;&amp;\d?|\d?(&gt;&gt;|&gt;|&lt;)|\d?&lt;&amp;|\d?&lt;&gt;</string>
			<key>name</key>
			<string>markup.inserted.redirect.shell</string>
		</dict>
		<key>cmd-rem</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.rem.cmd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.rem.cmd</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?i)(rem)\b(?!\s*/\?)(.*?)(?&lt;!\^)(?=$|&amp;|\||&lt;|&gt;)</string>
		</dict>
		<key>cmd-rem-colons</key>
		<dict>
			<key>match</key>
			<string>::.*(?=$|&amp;|\||&lt;|&gt;)</string>
			<key>name</key>
			<string>comment.rem.cmd</string>
		</dict>
		<key>cmd-reserved</key>
		<dict>
			<key>match</key>
			<string>\b(?i)(con|prn|aux|nul|com[1-9]|lpt[1-9])\b</string>
			<key>name</key>
			<string>keyword.reserved.cmd</string>
		</dict>
		<key>cmd-set</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.set.cmd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.key.cmd</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.cmd</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>markup.inserted.cmd</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?i)(set)(?!\s*/\?)\s*(/a|/p)?\s*([\w$]+)(=)</string>
		</dict>
		<key>cmd-setlocal</key>
		<dict>
			<key>match</key>
			<string>\b(?i)setlocal(\s+(enable|disable)(extensions|delayedexpansion))*</string>
			<key>name</key>
			<string>keyword.control.setlocal.cmd</string>
		</dict>
		<key>cmd-string-double</key>
		<dict>
			<key>match</key>
			<string>".*?"</string>
			<key>name</key>
			<string>string.quoted.double.cmd</string>
		</dict>
		<key>cmd-string-single</key>
		<dict>
			<key>match</key>
			<string>'.*?'</string>
			<key>name</key>
			<string>string.quoted.single.cmd</string>
		</dict>
		<key>cmd-title</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.echo.cmd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.echo.cmd</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?i)(title)\b(?!\s*/\?)(.*?)(?&lt;!\^)(?=$|&amp;|\||&lt;|&gt;)</string>
		</dict>
		<key>cmd-vars-args</key>
		<dict>
			<key>match</key>
			<string>%%?~?d?p?n?x?s?a?t?z?(\$PATH:)?[0-9a-zA-Z\*]</string>
			<key>name</key>
			<string>variable.parameter.argument.cmd</string>
		</dict>
		<key>cmd-vars-exclam</key>
		<dict>
			<key>match</key>
			<string>!.*?!</string>
			<key>name</key>
			<string>variable.parameter.exclamation.cmd</string>
		</dict>
		<key>cmd-vars-percent</key>
		<dict>
			<key>match</key>
			<string>%[\w$]+(:~-?\d+,-?\d+|:[^=%]+=[^=%]+)?%</string>
			<key>name</key>
			<string>variable.parameter.percent.cmd</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.cmd</string>
	<key>uuid</key>
	<string>E07EC438-7B75-4437-8AA1-DA94C1E6EACC</string>
</dict>
</plist>
