<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bat</string>
		<string>cmd</string>
	</array>
	<key>firstLineMatch</key>
	<string>(?i)^@echo off$</string>
	<key>name</key>
	<string>DOS/Windows Batch File</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#batch</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>batch</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cmd-echo-on</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-echo</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-uid</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-drive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-escape-caret</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-escape-for</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-escape-delayed</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-escape-find</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-parenthesis</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-argument</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-rem-colons</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-rem</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-setlocal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-set</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-defined</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-exist</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-if</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-reserved</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-net</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-reg</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-com</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-standard-exe</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-extended-exe</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-goto</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-internal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-indo</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-equ</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-label</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-executable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-path</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-file</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-punctuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-other</string>
				</dict>
			</array>
		</dict>
		<key>cmd-argument</key>
		<dict>
			<key>match</key>
			<string>(?i)%%?~?d?p?n?x?s?a?t?z?(\$PATH:)?[\da-z\*]</string>
			<key>name</key>
			<string>variable.argument.cmd</string>
		</dict>
		<key>cmd-com</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(chcp|diskcomp|diskcopy|format|graftabl|mode|more|tree)(\.com)?(?=$|[\ \t,;="''&amp;()/])</string>
			<key>name</key>
			<string>keyword.external.com.cmd</string>
		</dict>
		<key>cmd-defined</key>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=[\ \t,;]defined)\s*([\w\*\~\-\$]+)</string>
			<key>name</key>
			<string>variable.defined.cmd</string>
		</dict>
		<key>cmd-drive</key>
		<dict>
			<key>match</key>
			<string>(?i)\b([a-z]|http|ftp|file)(?=:)</string>
			<key>name</key>
			<string>support.function.drive.cmd</string>
		</dict>
		<key>cmd-echo</key>
		<dict>
			<key>begin</key>
			<string>(?i)\b(echo)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.echo.cmd</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$|(?:(?&lt;!\^)(&amp;|\||&lt;|&gt;))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.inserted.punctuation.cmd</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cmd-variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-argument</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-drive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-standard-exe</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-extended-exe</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-path</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-punctuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cmd-other</string>
				</dict>
			</array>
		</dict>
		<key>cmd-echo-on</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(echo)\s+(on|off|/\?)\s*(?=$|&amp;|\||&lt;|&gt;)</string>
			<key>name</key>
			<string>keyword.echo.cmd</string>
		</dict>
		<key>cmd-equ</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(equ|neq|lss|leq|gtr|geq)\b</string>
			<key>name</key>
			<string>keyword.operator.cmd</string>
		</dict>
		<key>cmd-escape-caret</key>
		<dict>
			<key>match</key>
			<string>\^[&amp;&lt;&gt;|^]|\^$</string>
			<key>name</key>
			<string>support.function.escape.caret.cmd</string>
		</dict>
		<key>cmd-escape-delayed</key>
		<dict>
			<key>match</key>
			<string>\^\^!</string>
			<key>name</key>
			<string>support.function.escape.delayed.cmd</string>
		</dict>
		<key>cmd-escape-find</key>
		<dict>
			<key>match</key>
			<string></string>
			<key>name</key>
			<string>support.function.escape.find.cmd</string>
		</dict>
		<key>cmd-escape-for</key>
		<dict>
			<key>match</key>
			<string>\^['`,;=()]</string>
			<key>name</key>
			<string>support.function.escape.for.cmd</string>
		</dict>
		<key>cmd-executable</key>
		<dict>
			<key>match</key>
			<string>(?i)[\w\*\~\-\$]+\.(com|exe|bat|cmd|vbs|vbe|js|jse|wsf|wsh|msc)(?=[\ "''])</string>
			<key>name</key>
			<string>keyword.executable.cmd</string>
		</dict>
		<key>cmd-exist</key>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=[\ \t,;]exist)\s*([\w\*\~\-\$]+)</string>
			<key>name</key>
			<string>support.function.folder.cmd</string>
		</dict>
		<key>cmd-extended-exe</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(makecab|expand|regedit|cmdow|cwnd|cscript|ping|grep|sed|msiexec|iexpress|modifype)(\.exe)?(?=$|[\ \t,;="''&amp;()/])</string>
			<key>name</key>
			<string>keyword.extended.exe.cmd</string>
		</dict>
		<key>cmd-file</key>
		<dict>
			<key>match</key>
			<string>[\w\*\~\-\$]*\.[\w\*\~\-\$]+</string>
			<key>name</key>
			<string>support.function.file.cmd</string>
		</dict>
		<key>cmd-goto</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(?&lt;=call|goto)\s*[\w\*\~\-]+</string>
			<key>name</key>
			<string>constant.other.colon.cmd</string>
		</dict>
		<key>cmd-if</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(if|not|else|exist|defined|errorlevel|cmdextversion)(?=$|[\ \t,;="&amp;()])</string>
			<key>name</key>
			<string>keyword.control.conditional.if.cmd</string>
		</dict>
		<key>cmd-indo</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(in|do)\b</string>
			<key>name</key>
			<string>keyword.control.repeat.cmd</string>
		</dict>
		<key>cmd-internal</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(assoc|break|call|cd|chdir|cls|color|copy|date|del|dir|endlocal|erase|exit|for|ftype|goto|if|md|mkdir|mklink|move|path|pause|popd|prompt|pushd|rd|rem|ren|rename|rmdir|set|setlocal|shift|start|time|title|type|ver|verify|vol)(?=$|[\ \t,;="&amp;()/])</string>
			<key>name</key>
			<string>keyword.internal.cmd</string>
		</dict>
		<key>cmd-label</key>
		<dict>
			<key>match</key>
			<string>:[\w\*\~\-\$]+</string>
			<key>name</key>
			<string>constant.other.colon.cmd</string>
		</dict>
		<key>cmd-net</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(net)(\.exe)?\s+(accounts|computer|config|continue|file|group|help|helpmsg|localgroup|pause|session|share|start|statistics|stop|time|use|user|view)(?=$|[\ \t,;="''&amp;()])</string>
			<key>name</key>
			<string>keyword.net.exe.cmd</string>
		</dict>
		<key>cmd-numbers</key>
		<dict>
			<key>match</key>
			<string>\d+</string>
			<key>name</key>
			<string>constant.numeric.cmd</string>
		</dict>
		<key>cmd-other</key>
		<dict>
			<key>match</key>
			<string>.</string>
			<key>name</key>
			<string>string.other.cmd</string>
		</dict>
		<key>cmd-parenthesis</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>markup.inserted.cmd</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#batch</string>
				</dict>
			</array>
		</dict>
		<key>cmd-path</key>
		<dict>
			<key>match</key>
			<string>(?i)([\w\*\~\-\.\$]+)(?=\\|/)|(?&lt;=\\|/)([\w\*\~\-\.\$]+)</string>
			<key>name</key>
			<string>support.function.path.cmd</string>
		</dict>
		<key>cmd-punctuation</key>
		<dict>
			<key>match</key>
			<string>[-+='"`*,\[\]\{\}@\\/:.;!?#~$¹þ^_\t\ \(\)&lt;&gt;&amp;%]</string>
			<key>name</key>
			<string>markup.inserted.punctuation.cmd</string>
		</dict>
		<key>cmd-reg</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(reg)(\.exe)?\s+(query|add|delete|copy|save|load|unload|restore|compare|export|import|flags)(?=$|[\ \t,;="''&amp;()])</string>
			<key>name</key>
			<string>keyword.reg.exe.cmd</string>
		</dict>
		<key>cmd-rem</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.rem.cmd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.inserted.punctuation.cmd</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.rem.cmd</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b(rem)(?!\s*/\?)([\ \t,;=])(.*?)$</string>
		</dict>
		<key>cmd-rem-colons</key>
		<dict>
			<key>match</key>
			<string>::.*$</string>
			<key>name</key>
			<string>comment.rem.cmd</string>
		</dict>
		<key>cmd-reserved</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(con|prn|aux|nul|com[1-9]|lpt[1-9])(?=$|[\ \t,;="&amp;()])</string>
			<key>name</key>
			<string>keyword.reserved.cmd</string>
		</dict>
		<key>cmd-set</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.set.cmd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.inserted.punctuation.cmd</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.function.key.cmd</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.cmd</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b(set)(?!\s*/\?)\s*(?:(/)([ap]))?[\ \t,;=]+([\w\*\~\-\$]+)</string>
		</dict>
		<key>cmd-setlocal</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(setlocal)(\s+(enable|disable)(extensions|delayedexpansion)){,2}(?=$|[\ \t,;="&amp;()])</string>
			<key>name</key>
			<string>keyword.control.setlocal.cmd</string>
		</dict>
		<key>cmd-standard-exe</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(attrib|bcdedit|cacls|chkdsk|chkntfs|cmd|comp|compact|convert|diskpart|doskey|driverquery|fc|find|findstr|fsutil|gpresult|help|icacls|label|openfiles|print|recover|replace|robocopy|sc|schtasks|shutdown|sort|subst|systeminfo|taskkill|tasklist|wmic|xcopy)(\.exe)?(?=$|[\ \t,;="''&amp;()/])</string>
			<key>name</key>
			<string>keyword.standard.exe.cmd</string>
		</dict>
		<key>cmd-uid</key>
		<dict>
			<key>match</key>
			<string>(?i)\b[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}</string>
			<key>name</key>
			<string>constant.numeric.uid.cmd</string>
		</dict>
		<key>cmd-variable</key>
		<dict>
			<key>match</key>
			<string>(!|%%|%)[\w\*\~\-\$]+(:~-?\d+|:~-?\d+,-?\d+|:[^=%]+=[^=%]+)?\1</string>
			<key>name</key>
			<string>variable.internal.cmd</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.cmd</string>
	<key>uuid</key>
	<string>E07EC438-7B75-4437-8AA1-DA94C1E6EACC</string>
</dict>
</plist>
